name: latibot
description: Pong!.
version: 4.0.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  nyxx: ^6.7.0
  ffi: ^2.1.4
  yaml: ^3.1.3
  nyxx_commands: ^6.0.4
  nyxx_lavalink: ^4.0.0-dev.1
  meta: ^1.17.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
